name: Semantic PR title

on:
  pull_request:
    types: [opened,edited]

jobs:
  verify-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

